/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dogago.ka.gid;

import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        radPABO = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        radCHICKEN = new javax.swing.JRadioButton();
        radPORK = new javax.swing.JRadioButton();
        chkROYAL = new javax.swing.JCheckBox();
        chkPEPSI = new javax.swing.JCheckBox();
        chkSPRITE = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtSUB = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtTAX = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtTOTAL = new javax.swing.JTextPane();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnENTER = new javax.swing.JButton();
        btnCLEAR = new javax.swing.JButton();
        btnEXIT = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(100, 240, 240));

        jLabel2.setBackground(new java.awt.Color(150, 240, 240));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 26)); // NOI18N
        jLabel2.setText("PASTIL NA MIX & MATCH");

        radPABO.setBackground(new java.awt.Color(200, 210, 240));
        radPABO.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        radPABO.setText("PABO          15.00");
        radPABO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radPABOActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("PASTIL TOPPINGS");

        radCHICKEN.setBackground(new java.awt.Color(180, 240, 240));
        radCHICKEN.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        radCHICKEN.setText("CHIKEN    10.00");
        radCHICKEN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radCHICKENActionPerformed(evt);
            }
        });

        radPORK.setBackground(new java.awt.Color(200, 190, 240));
        radPORK.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        radPORK.setText("PORK          10.00");
        radPORK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radPORKActionPerformed(evt);
            }
        });

        chkROYAL.setBackground(new java.awt.Color(255, 165, 0));
        chkROYAL.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        chkROYAL.setText("ROYAL       15.00");
        chkROYAL.setToolTipText("");
        chkROYAL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkROYALActionPerformed(evt);
            }
        });

        chkPEPSI.setBackground(new java.awt.Color(0, 150, 255));
        chkPEPSI.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        chkPEPSI.setText("PEPSI  BLUE      15.00");
        chkPEPSI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkPEPSIActionPerformed(evt);
            }
        });

        chkSPRITE.setBackground(new java.awt.Color(173, 255, 47));
        chkSPRITE.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        chkSPRITE.setText("SPRITE       15.00");
        chkSPRITE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkSPRITEActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("DRINKS");

        jScrollPane1.setViewportView(txtSUB);

        jScrollPane2.setViewportView(txtTAX);

        jScrollPane3.setViewportView(txtTOTAL);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("SubTotal");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Cash on hand");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("CHANGE");

        btnENTER.setBackground(new java.awt.Color(150, 240, 240));
        btnENTER.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnENTER.setForeground(new java.awt.Color(100, 0, 0));
        btnENTER.setText("Enter");
        btnENTER.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnENTERActionPerformed(evt);
            }
        });

        btnCLEAR.setBackground(new java.awt.Color(240, 100, 240));
        btnCLEAR.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnCLEAR.setText("Clear");
        btnCLEAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCLEARActionPerformed(evt);
            }
        });

        btnEXIT.setBackground(new java.awt.Color(240, 240, 140));
        btnEXIT.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnEXIT.setText("Exit");
        btnEXIT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEXITActionPerformed(evt);
            }
        });

        jLabel7.setBackground(new java.awt.Color(100, 220, 210));
        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(12, 120, 0));
        jLabel7.setText("SOLO ORDERS ONLY");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 438, Short.MAX_VALUE)
                        .addComponent(btnEXIT, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(102, 102, 102)
                                .addComponent(jLabel1)
                                .addGap(126, 126, 126)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(88, 88, 88)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(btnENTER, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(btnCLEAR, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGap(67, 67, 67)
                                                    .addComponent(jLabel6))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGap(42, 42, 42)
                                                    .addComponent(jLabel5)))
                                            .addGap(18, 18, 18))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addContainerGap()
                                            .addComponent(jLabel4)
                                            .addGap(18, 18, 18)))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 66, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(radPABO, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(radCHICKEN, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(radPORK, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(73, 73, 73)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chkPEPSI)
                            .addComponent(chkSPRITE, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(chkROYAL, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(186, 186, 186)
                        .addComponent(jLabel7)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radPABO, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chkROYAL, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radCHICKEN, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chkPEPSI, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radPORK, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chkSPRITE, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel5)
                        .addComponent(btnENTER, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnCLEAR, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addComponent(btnEXIT, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void radPABOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radPABOActionPerformed
        // TODO add your handling code here:
       if (radPABO.isSelected())
           radCHICKEN.setSelected(false);
           radPORK.setSelected(false);
                
    }//GEN-LAST:event_radPABOActionPerformed

    private void radCHICKENActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radCHICKENActionPerformed
        // TODO add your handling code here:
        if (radCHICKEN.isSelected())
           radPABO.setSelected(false);
           radPORK.setSelected(false);
    }//GEN-LAST:event_radCHICKENActionPerformed

    private void radPORKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radPORKActionPerformed
        // TODO add your handling code here:
        
        if (radPORK.isSelected())
           radPABO.setSelected(false);
           radCHICKEN.setSelected(false);
    }//GEN-LAST:event_radPORKActionPerformed

    private void chkROYALActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkROYALActionPerformed
        // TODO add your handling code here:
        
        if (chkROYAL.isSelected())
           chkPEPSI.setSelected(false);
           chkSPRITE.setSelected(false);
    }//GEN-LAST:event_chkROYALActionPerformed

    private void chkPEPSIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkPEPSIActionPerformed
        // TODO add your handling code here:
        if (chkPEPSI.isSelected())
           chkROYAL.setSelected(false);
           chkSPRITE.setSelected(false);
    }//GEN-LAST:event_chkPEPSIActionPerformed

    private void chkSPRITEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkSPRITEActionPerformed
        // TODO add your handling code here:
        if (chkSPRITE.isSelected())
           chkPEPSI.setSelected(false);
           chkROYAL.setSelected(false);
    }//GEN-LAST:event_chkSPRITEActionPerformed

    private void btnENTERActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnENTERActionPerformed
        // TODO add your handling code here:
        
        double total;
        double subtotal = 0;
       //double quantity = 0 ;
        final double TAXRATE = 0;
        double tax;
        //double quant;
        
        if (radPABO.isSelected()){
          // txtQNT.setText(Double.toString(subtotal));
          
            subtotal = subtotal + 15.00;
        }else if (radCHICKEN.isSelected()){
            subtotal=  subtotal + 10.00;
        }else if (radPORK.isSelected()){
            subtotal = subtotal + 10.00;
        }
        
        if (chkROYAL.isSelected()){
            subtotal = subtotal + 15.00;
        }else if (chkPEPSI.isSelected()){
            subtotal = subtotal + 15.00;
        }else if (chkSPRITE.isSelected()){
            subtotal = subtotal + 15.00;
        }
        
        //txtQNT.setText(Double.toString(quantity));
        txtSUB.setText(Double.toString(subtotal));
        
        subtotal = Double.parseDouble(txtSUB.getText());
       //quantity = Double.parseDouble(txtQNT.getText());
       //quantity = Integer.parseInt(txtQNT.getText());
        tax = Integer.parseInt(txtTAX.getText());
        
        total = subtotal - tax;
        
        txtTAX.setText(Double.toString(tax));
        
        txtTOTAL.setText(Double.toString(total));
    }//GEN-LAST:event_btnENTERActionPerformed

    private void btnEXITActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEXITActionPerformed
        // TODO add your handling code here:
        
        System.exit(0); 
    }//GEN-LAST:event_btnEXITActionPerformed

    private void btnCLEARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCLEARActionPerformed
        // TODO add your handling code here:
        radPABO.setSelected(false);
         radCHICKEN.setSelected(false);
          radPORK.setSelected(false);
           chkROYAL.setSelected(false);
            chkPEPSI.setSelected(false);
             chkSPRITE.setSelected(false);
             txtTOTAL.setText("");
             txtSUB.setText("");
             txtTAX.setText("");
             
    }//GEN-LAST:event_btnCLEARActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCLEAR;
    private javax.swing.JButton btnENTER;
    private javax.swing.JButton btnEXIT;
    private javax.swing.JCheckBox chkPEPSI;
    private javax.swing.JCheckBox chkROYAL;
    private javax.swing.JCheckBox chkSPRITE;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JRadioButton radCHICKEN;
    private javax.swing.JRadioButton radPABO;
    private javax.swing.JRadioButton radPORK;
    private javax.swing.JTextPane txtSUB;
    private javax.swing.JTextPane txtTAX;
    private javax.swing.JTextPane txtTOTAL;
    // End of variables declaration//GEN-END:variables
}
